  [functions]
    node_bundler = "esbuild"
    directory = "functions"
[functions.readTurso]
  external_node_modules = ["@libsql/client"]
[functions.addTurso]
  external_node_modules = ["@libsql/client"]
[functions.delTurso]
  external_node_modules = ["@libsql/client"]
[functions.chgTurso]
  external_node_modules = ["@libsql/client"]
[functions.delMuliTurso]
  external_node_modules = ["@libsql/client"]

[functions.readSupabase]
   external_node_modules = ["@supabase/supabase-js"]
